# Generated by Django 3.0.3 on 2020-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_nick',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_pid',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_team',
        ),
        migrations.AddField(
            model_name='player',
            name='p_club',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='p_gender',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='p_name',
            field=models.CharField(max_length=10),
        ),
    ]
