# Generated by Django 3.0.3 on 2020-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200719_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nname',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
