# Generated by Django 3.0.3 on 2020-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_recid',
            field=models.IntegerField(default=0),
        ),
    ]
