# Generated by Django 3.0.3 on 2020-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200722_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
