# Generated by Django 3.0.8 on 2020-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_major', models.CharField(max_length=30)),
                ('t_captain', models.CharField(max_length=30)),
                ('t_memCount', models.IntegerField(default=0)),
            ],
        ),
    ]
