# Generated by Django 3.0.3 on 2020-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_t_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_memo',
            field=models.TextField(),
        ),
    ]
