# Generated by Django 3.0.8 on 2020-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_pid', models.CharField(max_length=30)),
                ('p_nick', models.CharField(max_length=50)),
                ('p_email', models.CharField(max_length=30)),
                ('p_name', models.CharField(max_length=30)),
                ('p_birth', models.CharField(max_length=10)),
                ('p_position', models.CharField(max_length=30)),
                ('p_team', models.CharField(max_length=30)),
            ],
        ),
    ]
