# Generated by Django 3.0.3 on 2020-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200723_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='p_nname',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
