# Generated by Django 3.0.3 on 2020-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='t_memo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
