# Generated by Django 3.0.3 on 2020-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200723_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_comment', models.CharField(max_length=255)),
                ('c_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('c_writer', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
