# Generated by Django 3.0.3 on 2020-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200723_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='m_date',
            field=models.CharField(max_length=10),
        ),
    ]
