# Generated by Django 3.0.3 on 2020-07-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20200723_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='m_rival',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
