# Generated by Django 3.0.3 on 2020-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200723_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='m_rival',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
