# Generated by Django 3.0.3 on 2020-07-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20200723_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='m_num',
            field=models.IntegerField(default=0),
        ),
    ]
