# Generated by Django 3.0.3 on 2020-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='m_date',
            field=models.SmallIntegerField(max_length=4),
        ),
    ]
