# Generated by Django 3.0.3 on 2020-07-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_title', models.CharField(max_length=30)),
                ('r_memo', models.CharField(max_length=255)),
                ('r_writer', models.CharField(max_length=20)),
                ('r_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
